# Change these first
owner: torresgol10 # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

user-agent: Github-Upptime

sites:
  - name: banusproperty
    url: https://www.banusproperty.com  
  - name: bemontmarbella
    url: https://www.bemontmarbella.com  
  - name: benarrochrealestate
    url: https://www.benarrochrealestate.com  
  - name: bhhsmarbella
    url: https://www.bhhsmarbella.com  
  - name: callumswanrealty
    url: https://www.callumswanrealty.com  
  - name: campomarspain
    url: https://www.campomarspain.com  
  - name: costacoveta
    url: https://www.costacoveta.com  
  - name: deluxestates
    url: https://www.deluxestates.es  
  - name: dmproperties
    url: https://www.dmproperties.com  
  - name: drumelia
    url: https://www.drumelia.com  
  - name: excellentspain
    url: https://www.excellentspain.com  
  - name: futurehomesspain
    url: https://www.futurehomesspain.com  
  - name: gilmar-costadelsol
    url: https://www.gilmar-costadelsol.com  
  - name: holmesotogrande
    url: https://www.holmesotogrande.com  
  - name: inmo-andalucia
    url: http://www.inmo-andalucia.com  
  - name: ivardahl
    url: https://www.ivardahl.com  
  - name: keyrealestates
    url: https://www.keyrealestates.com  
  - name: lacostamarbella
    url: https://www.lacostamarbella.com  
  - name: libehomes
    url: https://www.libehomes.com  
  - name: lorainedezara
    url: https://www.lorainedezara.com  
  - name: marbella-hills-homes
    url: https://www.marbella-hills-homes.com  
  - name: marbellauniqueproperties
    url: https://www.marbellauniqueproperties.com  
  - name: mpdunne
    url: https://www.mpdunne.com  
  - name: nevadomarbella
    url: https://www.nevadomarbella.com  
  - name: prestige-expo
    url: https://www.prestige-expo.com  
  - name: propertypartners
    url: https://www.propertypartners.es  
  - name: purelivingproperties
    url: https://www.purelivingproperties.com  
  - name: seville-sothebysrealty
    url: https://www.seville-sothebysrealty.com  
  - name: spainsecondhome
    url: https://www.spainsecondhome.com  
  - name: terrameridiana
    url: https://www.terrameridiana.com

#Separacion

  - name: 2ndhousemarbella
    url: https://www.2ndhousemarbella.com  
  - name: absoluteprestige
    url: https://www.absoluteprestige.com  
  - name: altiusmarbella
    url: https://www.altiusmarbella.com  
  - name: andadev
    url: https://www.andadev.com  
  - name: azuremarbella
    url: https://www.azuremarbella.es  
  - name: casona6lunas
    url: https://www.casona6lunas.com  
  - name: cleoxinversiones
    url: https://www.cleoxinversiones.com  
  - name: cosmopolitan-properties
    url: https://www.cosmopolitan-properties.com  
  - name: costadelsol365
    url: https://www.costadelsol365.es  
  - name: crownmarbella
    url: https://www.crownmarbella.com  
  - name: elbosque8
    url: https://www.elbosque8.es  
  - name: elbosque9
    url: https://www.elbosque9.es  
  - name: elmiradormarbella
    url: https://www.elmiradormarbella.es  
  - name: elnidomarbella
    url: https://www.elnidomarbella.es  
  - name: eurojavea
    url: https://www.eurojavea.com  
  - name: gabrielarecalde
    url: https://www.gabrielarecalde.com  
  - name: gibraltarmls
    url: https://www.gibraltarmls.com  
  - name: golden7
    url: https://www.golden7.es  
  - name: hiddejames
    url: https://www.hiddejames.com  
  - name: homewatch
    url: https://www.homewatch.es  
  - name: inmoba
    url: https://www.inmoba.com  
  - name: inmobalia
    url: https://www.inmobalia.com  
  - name: lazagaleta19
    url: https://www.lazagaleta19.com  
  - name: luciapou
    url: https://www.luciapou.com  
  - name: magna-estates
    url: https://www.magna-estates.com  
  - name: malagamls
    url: https://www.malagamls.com  
  - name: marbella-ev
    url: https://www.marbella-ev.com  
  - name: me-estates
    url: https://www.me-estates.com  
  - name: mojoestates
    url: https://www.mojoestates.com  
  - name: njmarbella
    url: https://www.njmarbella.com  
  - name: noll-sotogrande
    url: https://www.noll-sotogrande.com  
  - name: nordicamarbella
    url: https://www.nordicamarbella.com  
  - name: privateproperty
    url: https://www.privateproperty.es  
  - name: propertytop
    url: https://www.propertytop.com  
  - name: sbe-realty
    url: https://www.sbe-realty.com  
  - name: selectionmed
    url: https://www.selectionmed.com  
  - name: sierrablanca37
    url: https://www.sierrablanca37.com  
  - name: solvilla
    url: https://www.solvilla-no  
  - name: sotograndeigp
    url: https://www.sotograndeigp.es  
  - name: sotograndemls
    url: https://www.sotograndemls.com  
  - name: sotogrande-properties
    url: https://www.sotogrande-properties.com  
  - name: stunningfincas
    url: https://www.stunningfincas.com  
  - name: terramarbella
    url: https://www.terramarbella.com  
  - name: teseoestate
    url: https://www.teseoestate.com  
  - name: villa-angulo-marbella
    url: https://www.villa-angulo-marbella.com  
  - name: villamayor-one
    url: https://www.villamayor-one.com  
  - name: villasfincas
    url: https://www.villasfincas.com  
  - name: villa-verano-marbella
    url: https://www.villa-verano-marbella.com
    
assignees:
  - torresgol10
  
status-website:
  theme: night
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/torresgol10/upptime
workflowSchedule:
  uptime: "*/5 * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
